# Generated by Django 5.2.6 on 2025-11-01 20:38

from django.db import migrations

def create_groups_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    admin, created = Group.objects.get_or_create(name="Administrator")
    shopkeeper, created = Group.objects.get_or_create(name="Shopkeeper")
    manager, created = Group.objects.get_or_create(name="Manager")
    carrier, created = Group.objects.get_or_create(name="Carrier")

    #admin permissions
    all_permissions = Permission.objects.all()
    admin.permissions(all_permissions)

    #shopkeeper permissions
    shopkeeper_permissions = Permission.objects.filter(
        codename__in=[
            'add_order', 'change_order', 'delete_order', 'view_order',
            'add_store', 'change_store', 'delete_store', 'view_store',
            'add_address', 'change_address', 'delete_address', 'view_address',
            'change_user', 'view_user', 'delete_user'
        ]
    )
    shopkeeper.permissions.set(shopkeeper_permissions)

    #manager
    manager_permissions = Permission.objects.filter(
        codename__in=[
            'add_trip', 'change_trip', 'delete_trip', 'view_trip',
            'add_depot', 'change_depot', 'delete_depot', 'view_depot',
            'add_address', 'change_address', 'delete_address', 'view_address',
            'change_user', 'view_user', 'delete_user',
            'view_truck','view_order'
            'view_box', 'add_box', 'change_box', 'delete_box'
        ])
    manager.permissions.set(manager_permissions)

    #carrier
    carrier_permissions = Permission.objects.filter(
        codename_in= [
            'add_carrier', 'change_carrier', 'delete_carrier', 'view_carrier',
            'add_truck', 'change_truck', 'delete_truck', 'view_truck',
            'add_address', 'change_address', 'delete_address', 'view_address',
            'change_user', 'view_user', 'delete_user'
        ]
    )


class Migration(migrations.Migration):


    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups_permissions)
    ]
