# Generated by Django 5.2.6 on 2025-10-04 19:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_location_alter_user_age_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='depot',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='depot',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='user_id',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7)),
                ('axles_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(11)])),
                ('cargo_lenght', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('cargo_widht', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('cargo_height', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('max_payload_kg', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('cargo_volume_m3', models.FloatField(blank=True, null=True)),
                ('euro', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('is_active', models.BooleanField()),
                ('release_year', models.PositiveIntegerField()),
                ('total_trips', models.PositiveIntegerField()),
                ('max_fuel_capacity', models.PositiveIntegerField()),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrier')),
            ],
        ),
    ]
