# Generated by Django 5.2.6 on 2025-11-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_create_roles_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="total_distance_km",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="trip",
            name="arrival_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="departure_date",
            field=models.DateTimeField(null=True),
        ),
    ]
