# Generated by Django 5.2.6 on 2025-10-05 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_location_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='cargo_lenght',
            new_name='cargo_length',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='cargo_widht',
            new_name='cargo_width',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Man', 'Manager'), ('Shop', 'Shopkeeper'), ('Carr', 'Carrier')], max_length=4),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pend', 'Pending'), ('Sche', 'Scheduled'), ('Ship', 'Shipped'), ('Deli', 'Delivered'), ('Canc', 'Cancelled')], max_length=4)),
                ('total_weight_kg', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('total_volume_m3', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('total_boxes', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('scheduled', models.BooleanField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.store')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Sma', 'Small'), ('Med', 'Medium'), ('Big', 'Big'), ('Lar', 'Large'), ('Cus', 'Custom')], max_length=3)),
                ('length', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('width', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('height', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('payload_kg', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('volume_m3', models.FloatField(blank=True, null=True)),
                ('was_delivered', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('total_loaded_weight_kg', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('total_loaded_volume_m3', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('excess_weight_flag', models.BooleanField(default=False)),
                ('excess_weight_fine_amount', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.01))),
                ('carbon_kg_co2', models.FloatField()),
                ('status', models.CharField(choices=[('Plan', 'Planned'), ('InTr', 'In_Transit'), ('Comp', 'Completed'), ('Canc', 'Cancelled')], max_length=4)),
                ('origin_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.depot')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.truck')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trip'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.store')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trip')),
            ],
        ),
    ]
