# Generated by Django 5.2.6 on 2025-11-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_trip_total_distance_km_alter_trip_arrival_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrier",
            name="contact",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="depot",
            name="contact",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="store",
            name="contact",
            field=models.CharField(max_length=11),
        ),
    ]
