# Generated by Django 5.2.6 on 2025-11-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_carrier_contact_alter_depot_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="scheduled",
        ),
    ]
