# Generated by Django 5.2.6 on 2025-10-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_cargo_lenght_truck_cargo_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='plate',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
