# Generated by Django 5.2.6 on 2025-10-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_address_cep_alter_truck_plate_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(max_length=10),
        ),
    ]
