# Generated by Django 5.2.6 on 2025-10-24 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_address_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_boxes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_volume_m3',
            field=models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.0)),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_weight_kg',
            field=models.FloatField(verbose_name=django.core.validators.MinValueValidator(0.0)),
        ),
        migrations.AlterField(
            model_name='order',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trip'),
        ),
    ]
