# Generated by Django 5.2.6 on 2025-10-27 13:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_total_boxes_alter_order_total_volume_m3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='excess_weight_fine_amount',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='excess_weight_flag',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='carbon_kg_co2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin_depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.depot'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.truck'),
        ),
    ]
